# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8069a0f09d1f36c1a3bc529a071d9fe79457d3ff1f30ec9619d755d2427da1c79c33751904b41c3b4c67d6cd0891ebb704fabf62c067bd3e2bf64eb8c8954fa0

test:
  secret_key_base: c2e587a2c031344ebd84cf0a6d6fedc161a38cb03d9d04c2d03f010b4732e8c6541d0882fe5dd03c32391488b42a4b8abea13e1ae9988ef84b7e0a5f92e0d962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
